// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import './login.css';
import '../globals.css';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="sesion-container">
        <header>
          <div className='container-header'>
            <div className='logo'></div>
            <div className='header-text'>Inicio</div>
          </div>
        </header>
        <div style={{ display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', maxWidth: '100vw', height: '500px ', padding: '0 20px' }}>
          {children}
        </div>
      </body>
    </html>
  );
}
